### ISSUE TITLE
Partial Tab Completion - Current Directory

### ISSUE THREAD

**Issue by TerminalFi** [Arrexel/phpbash#17]
Hello, Feature Enhancement with ehh 20 lines of code or less.

Tab completion for the currently directory. 

Upon issuing the `cd` command execute a `ls -a` command a populate a `var currentDirListing = []` array with entire folder contents. Capture tab key and cycle through the files.

Rinse and repeat.

If I finish my college test prior to hearing back. I'll submit a PR

**Comment by Arrexel** [comment]
Sorry I've had a busy week! It's on my to-do list unless you want to submit a PR
