### ISSUE TITLE
ERROR :: sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by harishoss** [Arrexel/phpbash#22]
I created a t2.micro VM instance to test this out. 
I just tried to create a folder 
``` sudo mkdir testdir  ```

and I got this error
``` sudo: no tty present and no askpass program specified ```

I know this to deal with permissions on my server-side. but I don't know how to do so.

any help?

**Comment by TerminalFi** [comment]
> I created a t2.micro VM instance to test this out.
> I just tried to create a folder
> `sudo mkdir testdir `
> 
> and I got this error
> `sudo: no tty present and no askpass program specified`
> 
> I know this to deal with permissions on my server-side. but I don't know how to do so.
> 
> any help?

On the server you need to make it so that you don't need a password for sudo.

in your sudoer's file you need something like


`username ALL=(ALL) NOPASSWD:ALL`

**Comment by harishoss** [comment]
solved !! Thank you.
