### ISSUE TITLE
phpBash not responding 

### ISSUE THREAD

**Issue by touhidshaikh** [Arrexel/phpbash#6]
after typing vi or nano command.
phpbash not responding any command.

example : 
www-data@localhost:/var/www/html/phpbash# nano filename
or 
www-data@localhost:/var/www/html/phpbash# vi

**Comment by Arrexel** [comment]
phpbash is non-interactive, and will not work with commands like nano/vi/su/etc. I tested after some recent changes and it no longer hangs when attempting these commands, so I will close this for now.
